language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python modules/graphics_test.py
  - python modules/party_test.py
  - python modules/storage_test.py